export const INIT = 'INIT';
export const SET_STATUS_BAR_COLOR = 'SET_STATUS_BAR_COLOR';
export const SET_ROUTER_COLOR = 'SET_ROUTER_COLOR';
export const SET_IS_AUTHORIZED = 'SET_IS_AUTHORIZED';
export const AUTH_LOADING = 'AUTH_LOADING';
export const ALERT_AUTHORIZATION = 'ALERT_AUTHORIZATION';
export const SET_USER_KYC_STATUS = 'SET_USER_KYC_STATUS';

export const KYC_LOADING = 'KYC_LOADING';
export const ALERT_KYC = 'ALERT_KYC';
export const SET_REDIRECT_URL = 'SET_REDIRECT_URL';
export const GET_COUNTRIES = 'GET_COUNTRIES';
export const SET_USER_KYC_DATA = 'SET_USER_KYC_DATA';
export const SET_USER_WALLET_STATUS = 'SET_USER_WALLET_STATUS';
export const GET_USER_EXPERIENCE = 'GET_USER_EXPERIENCE';
export const SET_USER_EXPERIENCE = 'SET_USER_EXPERIENCE';
export const GET_KYC_DOCS = 'GET_KYC_DOCS';
export const SET_INVESTMENT_ID = 'SET_INVESTMENT_ID';

export const GET_TOKENS_HOME_SCREEN = 'GET_TOKENS_HOME_SCREEN';
export const GET_USER_TOKENS = 'GET_USER_TOKENS';
export const LOADING_TOKENS = 'LOADING_TOKENS';
export const GET_TOKEN_PROPERTIES = 'GET_TOKEN_PROPERTIES';
export const GET_TOKEN_BY_ID = 'GET_TOKEN_BY_ID';
export const GET_SELECTED_PROPERTY = 'GET_SELECTED_PROPERTY';

export const GET_TOKENS_GRAPH = 'GET_TOKENS_GRAPH';

export const GET_TERMS = 'GET_TERMS';
export const GET_FAQ = 'GET_FAQ';
export const SETTINGS_LOADING = 'SETTINGS_LOADING';
export const GET_USER_INFO = 'GET_USER_INFO';

export const LOADING_TRANSACTIONS = 'LOADING_TRANSACTIONS';
export const GET_PENDING_TRANSACTIONS = 'GET_PENDING_TRANSACTIONS';
export const GET_TRANSACTION_DOCS = 'GET_TRANSACTION_DOCS';
